### ISSUE TITLE
semantic menu can't use current_page? b/c it doesn't have a reference to the controller instance

### ISSUE THREAD

**Issue by ajsharp** [danielharan/semantic-menu#1]
This is due to how the controller instance is passed into the SemanticMenu intializer. Still, to get this instance to each 
    module MenuHelper
      def semantic_menu(opts={}, &block)
        # controller is not available in this context, but @controller is
        SemanticMenu.new(opts, &block).to_s(controller)
      end
    end

```
#...
ActionView::Base.send :include, MenuHelper
```

Additionally, we need to fix how the child menu items are being passed a controller instance.

```
class SemanticMenu < MenuItem

  def initialize(opts={},&block)
    @opts = {:class => 'menu'}.merge opts
    @level = 0
    @children = []

    yield self if block_given?
  end

  def to_s(controller=nil)
    @controller = controller
    # we need to pass the @controller instance to each child as well
    content_tag(:ul, @children.collect(&:to_s).join, @opts)
  end
end
```

**Comment by ajsharp** [comment]
I've forked, patched, and submitted a pull request. Here's the patch commit: http://github.com/ajsharp/semantic-menu/commit/40f6be8f168061931b541c44502ab06513588bc0

Thanks for this plugin, I LOVE the simplicity of it!

**Comment by danielharan** [comment]
reverted changes that caused this
