### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by alankirk** [danielharan/semantic-menu#2]
Hi there,

I've just installed the plugin, but when i try out the example code in my view:

<%= semantic_menu :class => 'top_level_nav' do |root|
  root.add "overview", "root_path"
end %>

I get the following error:

uninitialized class variable @@controller in MenuItem

Any help would be greatly appreciated, i'm hoping i've done something daft.

Thanks in advance

**Comment by danielharan** [comment]
should be fixed by commit 9d8f681dab073d73ea56 - thanks for bringing this to my attention.
