### ISSUE TITLE
Incompatible with Rails 3

### ISSUE THREAD

**Issue by yholkamp** [danielharan/semantic-menu#4]
The current version is sadly incompatible with Rails 3. The following stack is displayed when attempting to use it:

"undefined local variable or method `request' for #<MenuItem:0xa1c9c88>"
actionpack (3.0.0.beta4) lib/action_view/helpers/url_helper.rb:570:in`current_page?'
vendor/plugins/semantic-menu/lib/semantic_menu.rb:42:in `on_current_page?'
vendor/plugins/semantic-menu/lib/semantic_menu.rb:37:in`active?'
vendor/plugins/semantic-menu/lib/semantic_menu.rb:25:in `to_s'
vendor/plugins/semantic-menu/lib/semantic_menu.rb:58:in`collect'
vendor/plugins/semantic-menu/lib/semantic_menu.rb:58:in `to_s'
vendor/plugins/semantic-menu/lib/menu_helper.rb:19:in`semantic_menu'
actionpack (3.0.0.beta4) lib/action_view/template.rb:134:in `block in render'
...

Hopefully this can be fixed, I'll update this issue in case I come across any!

**Comment by danielharan** [comment]
Not a bug; please fork and use a pull request. Your current patch has a lot of extraneous changes, doesn't have tests and probably isn't backwards compatible. A worthwhile addition though.
